version: '3'
services:
  web:
    image: nginx
    container_name: servidor_exercicio_docker
    ports: 
    - 80:80
  mysql:
    image: mysql:latest
    container_name: banco_de_dados
    environment:
      - MYSQL_ROOT_PASSWORD=teste1234
    ports:
    - 3308:3306